name: Deploy to Render.com

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build client
        run: |
          cd client
          npm install
          npm run build

      - name: Move client build to server
        run: mv client/dist express-server/

      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}

      - name: Clean up
        run: |
              rm -rf express-server/dist
              rm -rf client/node_modules
