name: Deploy to Render.com

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build client
        run: |
          cd client
          npm install
          VITE_APP_CLOUD_NAME=${{ secrets.VITE_APP_CLOUD_NAME }} VITE_APP_PRESET=${{ secrets.VITE_APP_PRESET }} VITE_APP_BASE_URL="/api" npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: client/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: client/

      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
